#!/usr/bin/env python
# encoding: utf-8
#
# Copyright © 2014 deanishe@deanishe.net
#
# MIT Licence. See http://opensource.org/licenses/MIT
#
# Created on 2014-06-28
#

"""
"""

import sys
import os

if sys.version < '3':
    from codecs import unicode_escape_decode

    def u(x):
        return unicode_escape_decode(x)[0]

else:
    def u(x):
        return x

DEBUG = True

# Default size of icons
SIZE = 128  # px

basedir = os.path.abspath(os.path.dirname(__file__))

# Directory to save generated icons to
CACHEDIR = os.path.join(basedir, 'iconserver', 'static', 'icons')
# URL to CACHEDIR
CACHEURL = None
# CACHEURL = 'http://localhost:5000/static/icons'

# Where the TTF fonts are saved
FONTDIR = os.path.join(basedir, 'iconserver', 'static', 'fonts')

LOG_PATH = os.path.join(basedir, 'log', 'iconserver.log')
LOG_SIZE = 1024 * 1024  # 1 MB

# Administrators
ADMINS = ['deanishe@deanishe.net']

USE_LOCAL_MAIL = True

FONTS = {
    'fontawesome': {
        'name': 'Font Awesome',
        'ttf': 'fontawesome-webfont.ttf',
        'credit': 'Dave Gandy',
        'url': 'http://fortawesome.github.io/Font-Awesome/',
        'licence': 'http://scripts.sil.org/OFL',
        # 'woff': 'fontawesome-webfont.woff',
        'css': 'font-awesome.css',
        'classgen': lambda s: 'fa fa-' + s,
        'characters': {
            'adjust': u('\uf042'),
            'adn': u('\uf170'),
            'align-center': u('\uf037'),
            'align-justify': u('\uf039'),
            'align-left': u('\uf036'),
            'align-right': u('\uf038'),
            'ambulance': u('\uf0f9'),
            'anchor': u('\uf13d'),
            'android': u('\uf17b'),
            'angle-double-down': u('\uf103'),
            'angle-double-left': u('\uf100'),
            'angle-double-right': u('\uf101'),
            'angle-double-up': u('\uf102'),
            'angle-down': u('\uf107'),
            'angle-left': u('\uf104'),
            'angle-right': u('\uf105'),
            'angle-up': u('\uf106'),
            'apple': u('\uf179'),
            'archive': u('\uf187'),
            'arrow-circle-down': u('\uf0ab'),
            'arrow-circle-left': u('\uf0a8'),
            'arrow-circle-o-down': u('\uf01a'),
            'arrow-circle-o-left': u('\uf190'),
            'arrow-circle-o-right': u('\uf18e'),
            'arrow-circle-o-up': u('\uf01b'),
            'arrow-circle-right': u('\uf0a9'),
            'arrow-circle-up': u('\uf0aa'),
            'arrow-down': u('\uf063'),
            'arrow-left': u('\uf060'),
            'arrow-right': u('\uf061'),
            'arrow-up': u('\uf062'),
            'arrows': u('\uf047'),
            'arrows-alt': u('\uf0b2'),
            'arrows-h': u('\uf07e'),
            'arrows-v': u('\uf07d'),
            'asterisk': u('\uf069'),
            'automobile': u('\uf1b9'),
            'backward': u('\uf04a'),
            'ban': u('\uf05e'),
            'bank': u('\uf19c'),
            'bar-chart-o': u('\uf080'),
            'barcode': u('\uf02a'),
            'bars': u('\uf0c9'),
            'beer': u('\uf0fc'),
            'behance': u('\uf1b4'),
            'behance-square': u('\uf1b5'),
            'bell': u('\uf0f3'),
            'bell-o': u('\uf0a2'),
            'bitbucket': u('\uf171'),
            'bitbucket-square': u('\uf172'),
            'bitcoin': u('\uf15a'),
            'bold': u('\uf032'),
            'bolt': u('\uf0e7'),
            'bomb': u('\uf1e2'),
            'book': u('\uf02d'),
            'bookmark': u('\uf02e'),
            'bookmark-o': u('\uf097'),
            'briefcase': u('\uf0b1'),
            'btc': u('\uf15a'),
            'bug': u('\uf188'),
            'building': u('\uf1ad'),
            'building-o': u('\uf0f7'),
            'bullhorn': u('\uf0a1'),
            'bullseye': u('\uf140'),
            'cab': u('\uf1ba'),
            'calendar': u('\uf073'),
            'calendar-o': u('\uf133'),
            'camera': u('\uf030'),
            'camera-retro': u('\uf083'),
            'car': u('\uf1b9'),
            'caret-down': u('\uf0d7'),
            'caret-left': u('\uf0d9'),
            'caret-right': u('\uf0da'),
            'caret-square-o-down': u('\uf150'),
            'caret-square-o-left': u('\uf191'),
            'caret-square-o-right': u('\uf152'),
            'caret-square-o-up': u('\uf151'),
            'caret-up': u('\uf0d8'),
            'certificate': u('\uf0a3'),
            'chain': u('\uf0c1'),
            'chain-broken': u('\uf127'),
            'check': u('\uf00c'),
            'check-circle': u('\uf058'),
            'check-circle-o': u('\uf05d'),
            'check-square': u('\uf14a'),
            'check-square-o': u('\uf046'),
            'chevron-circle-down': u('\uf13a'),
            'chevron-circle-left': u('\uf137'),
            'chevron-circle-right': u('\uf138'),
            'chevron-circle-up': u('\uf139'),
            'chevron-down': u('\uf078'),
            'chevron-left': u('\uf053'),
            'chevron-right': u('\uf054'),
            'chevron-up': u('\uf077'),
            'child': u('\uf1ae'),
            'circle': u('\uf111'),
            'circle-o': u('\uf10c'),
            'circle-o-notch': u('\uf1ce'),
            'circle-thin': u('\uf1db'),
            'clipboard': u('\uf0ea'),
            'clock-o': u('\uf017'),
            'cloud': u('\uf0c2'),
            'cloud-download': u('\uf0ed'),
            'cloud-upload': u('\uf0ee'),
            'cny': u('\uf157'),
            'code': u('\uf121'),
            'code-fork': u('\uf126'),
            'codepen': u('\uf1cb'),
            'coffee': u('\uf0f4'),
            'cog': u('\uf013'),
            'cogs': u('\uf085'),
            'columns': u('\uf0db'),
            'comment': u('\uf075'),
            'comment-o': u('\uf0e5'),
            'comments': u('\uf086'),
            'comments-o': u('\uf0e6'),
            'compass': u('\uf14e'),
            'compress': u('\uf066'),
            'copy': u('\uf0c5'),
            'credit-card': u('\uf09d'),
            'crop': u('\uf125'),
            'crosshairs': u('\uf05b'),
            'css3': u('\uf13c'),
            'cube': u('\uf1b2'),
            'cubes': u('\uf1b3'),
            'cut': u('\uf0c4'),
            'cutlery': u('\uf0f5'),
            'dashboard': u('\uf0e4'),
            'database': u('\uf1c0'),
            'dedent': u('\uf03b'),
            'delicious': u('\uf1a5'),
            'desktop': u('\uf108'),
            'deviantart': u('\uf1bd'),
            'digg': u('\uf1a6'),
            'dollar': u('\uf155'),
            'dot-circle-o': u('\uf192'),
            'download': u('\uf019'),
            'dribbble': u('\uf17d'),
            'dropbox': u('\uf16b'),
            'drupal': u('\uf1a9'),
            'edit': u('\uf044'),
            'eject': u('\uf052'),
            'ellipsis-h': u('\uf141'),
            'ellipsis-v': u('\uf142'),
            'empire': u('\uf1d1'),
            'envelope': u('\uf0e0'),
            'envelope-o': u('\uf003'),
            'envelope-square': u('\uf199'),
            'eraser': u('\uf12d'),
            'eur': u('\uf153'),
            'euro': u('\uf153'),
            'exchange': u('\uf0ec'),
            'exclamation': u('\uf12a'),
            'exclamation-circle': u('\uf06a'),
            'exclamation-triangle': u('\uf071'),
            'expand': u('\uf065'),
            'external-link': u('\uf08e'),
            'external-link-square': u('\uf14c'),
            'eye': u('\uf06e'),
            'eye-slash': u('\uf070'),
            'facebook': u('\uf09a'),
            'facebook-square': u('\uf082'),
            'fast-backward': u('\uf049'),
            'fast-forward': u('\uf050'),
            'fax': u('\uf1ac'),
            'female': u('\uf182'),
            'fighter-jet': u('\uf0fb'),
            'file': u('\uf15b'),
            'file-archive-o': u('\uf1c6'),
            'file-audio-o': u('\uf1c7'),
            'file-code-o': u('\uf1c9'),
            'file-excel-o': u('\uf1c3'),
            'file-image-o': u('\uf1c5'),
            'file-movie-o': u('\uf1c8'),
            'file-o': u('\uf016'),
            'file-pdf-o': u('\uf1c1'),
            'file-photo-o': u('\uf1c5'),
            'file-picture-o': u('\uf1c5'),
            'file-powerpoint-o': u('\uf1c4'),
            'file-sound-o': u('\uf1c7'),
            'file-text': u('\uf15c'),
            'file-text-o': u('\uf0f6'),
            'file-video-o': u('\uf1c8'),
            'file-word-o': u('\uf1c2'),
            'file-zip-o': u('\uf1c6'),
            'files-o': u('\uf0c5'),
            'film': u('\uf008'),
            'filter': u('\uf0b0'),
            'fire': u('\uf06d'),
            'fire-extinguisher': u('\uf134'),
            'flag': u('\uf024'),
            'flag-checkered': u('\uf11e'),
            'flag-o': u('\uf11d'),
            'flash': u('\uf0e7'),
            'flask': u('\uf0c3'),
            'flickr': u('\uf16e'),
            'floppy-o': u('\uf0c7'),
            'folder': u('\uf07b'),
            'folder-o': u('\uf114'),
            'folder-open': u('\uf07c'),
            'folder-open-o': u('\uf115'),
            'font': u('\uf031'),
            'forward': u('\uf04e'),
            'foursquare': u('\uf180'),
            'frown-o': u('\uf119'),
            'gamepad': u('\uf11b'),
            'gavel': u('\uf0e3'),
            'gbp': u('\uf154'),
            'ge': u('\uf1d1'),
            'gear': u('\uf013'),
            'gears': u('\uf085'),
            'gift': u('\uf06b'),
            'git': u('\uf1d3'),
            'git-square': u('\uf1d2'),
            'github': u('\uf09b'),
            'github-alt': u('\uf113'),
            'github-square': u('\uf092'),
            'gittip': u('\uf184'),
            'glass': u('\uf000'),
            'globe': u('\uf0ac'),
            'google': u('\uf1a0'),
            'google-plus': u('\uf0d5'),
            'google-plus-square': u('\uf0d4'),
            'graduation-cap': u('\uf19d'),
            'group': u('\uf0c0'),
            'h-square': u('\uf0fd'),
            'hacker-news': u('\uf1d4'),
            'hand-o-down': u('\uf0a7'),
            'hand-o-left': u('\uf0a5'),
            'hand-o-right': u('\uf0a4'),
            'hand-o-up': u('\uf0a6'),
            'hdd-o': u('\uf0a0'),
            'header': u('\uf1dc'),
            'headphones': u('\uf025'),
            'heart': u('\uf004'),
            'heart-o': u('\uf08a'),
            'history': u('\uf1da'),
            'home': u('\uf015'),
            'hospital-o': u('\uf0f8'),
            'html5': u('\uf13b'),
            'image': u('\uf03e'),
            'inbox': u('\uf01c'),
            'indent': u('\uf03c'),
            'info': u('\uf129'),
            'info-circle': u('\uf05a'),
            'inr': u('\uf156'),
            'instagram': u('\uf16d'),
            'institution': u('\uf19c'),
            'italic': u('\uf033'),
            'joomla': u('\uf1aa'),
            'jpy': u('\uf157'),
            'jsfiddle': u('\uf1cc'),
            'key': u('\uf084'),
            'keyboard-o': u('\uf11c'),
            'krw': u('\uf159'),
            'language': u('\uf1ab'),
            'laptop': u('\uf109'),
            'leaf': u('\uf06c'),
            'legal': u('\uf0e3'),
            'lemon-o': u('\uf094'),
            'level-down': u('\uf149'),
            'level-up': u('\uf148'),
            'life-bouy': u('\uf1cd'),
            'life-ring': u('\uf1cd'),
            'life-saver': u('\uf1cd'),
            'lightbulb-o': u('\uf0eb'),
            'link': u('\uf0c1'),
            'linkedin': u('\uf0e1'),
            'linkedin-square': u('\uf08c'),
            'linux': u('\uf17c'),
            'list': u('\uf03a'),
            'list-alt': u('\uf022'),
            'list-ol': u('\uf0cb'),
            'list-ul': u('\uf0ca'),
            'location-arrow': u('\uf124'),
            'lock': u('\uf023'),
            'long-arrow-down': u('\uf175'),
            'long-arrow-left': u('\uf177'),
            'long-arrow-right': u('\uf178'),
            'long-arrow-up': u('\uf176'),
            'magic': u('\uf0d0'),
            'magnet': u('\uf076'),
            'mail-forward': u('\uf064'),
            'mail-reply': u('\uf112'),
            'mail-reply-all': u('\uf122'),
            'male': u('\uf183'),
            'map-marker': u('\uf041'),
            'maxcdn': u('\uf136'),
            'medkit': u('\uf0fa'),
            'meh-o': u('\uf11a'),
            'microphone': u('\uf130'),
            'microphone-slash': u('\uf131'),
            'minus': u('\uf068'),
            'minus-circle': u('\uf056'),
            'minus-square': u('\uf146'),
            'minus-square-o': u('\uf147'),
            'mobile': u('\uf10b'),
            'mobile-phone': u('\uf10b'),
            'money': u('\uf0d6'),
            'moon-o': u('\uf186'),
            'mortar-board': u('\uf19d'),
            'music': u('\uf001'),
            'navicon': u('\uf0c9'),
            'openid': u('\uf19b'),
            'outdent': u('\uf03b'),
            'pagelines': u('\uf18c'),
            'paper-plane': u('\uf1d8'),
            'paper-plane-o': u('\uf1d9'),
            'paperclip': u('\uf0c6'),
            'paragraph': u('\uf1dd'),
            'paste': u('\uf0ea'),
            'pause': u('\uf04c'),
            'paw': u('\uf1b0'),
            'pencil': u('\uf040'),
            'pencil-square': u('\uf14b'),
            'pencil-square-o': u('\uf044'),
            'phone': u('\uf095'),
            'phone-square': u('\uf098'),
            'photo': u('\uf03e'),
            'picture-o': u('\uf03e'),
            'pied-piper': u('\uf1a7'),
            'pied-piper-alt': u('\uf1a8'),
            'pied-piper-square': u('\uf1a7'),
            'pinterest': u('\uf0d2'),
            'pinterest-square': u('\uf0d3'),
            'plane': u('\uf072'),
            'play': u('\uf04b'),
            'play-circle': u('\uf144'),
            'play-circle-o': u('\uf01d'),
            'plus': u('\uf067'),
            'plus-circle': u('\uf055'),
            'plus-square': u('\uf0fe'),
            'plus-square-o': u('\uf196'),
            'power-off': u('\uf011'),
            'print': u('\uf02f'),
            'puzzle-piece': u('\uf12e'),
            'qq': u('\uf1d6'),
            'qrcode': u('\uf029'),
            'question': u('\uf128'),
            'question-circle': u('\uf059'),
            'quote-left': u('\uf10d'),
            'quote-right': u('\uf10e'),
            'ra': u('\uf1d0'),
            'random': u('\uf074'),
            'rebel': u('\uf1d0'),
            'recycle': u('\uf1b8'),
            'reddit': u('\uf1a1'),
            'reddit-square': u('\uf1a2'),
            'refresh': u('\uf021'),
            'renren': u('\uf18b'),
            'reorder': u('\uf0c9'),
            'repeat': u('\uf01e'),
            'reply': u('\uf112'),
            'reply-all': u('\uf122'),
            'retweet': u('\uf079'),
            'rmb': u('\uf157'),
            'road': u('\uf018'),
            'rocket': u('\uf135'),
            'rotate-left': u('\uf0e2'),
            'rotate-right': u('\uf01e'),
            'rouble': u('\uf158'),
            'rss': u('\uf09e'),
            'rss-square': u('\uf143'),
            'rub': u('\uf158'),
            'ruble': u('\uf158'),
            'rupee': u('\uf156'),
            'save': u('\uf0c7'),
            'scissors': u('\uf0c4'),
            'search': u('\uf002'),
            'search-minus': u('\uf010'),
            'search-plus': u('\uf00e'),
            'send': u('\uf1d8'),
            'send-o': u('\uf1d9'),
            'share': u('\uf064'),
            'share-alt': u('\uf1e0'),
            'share-alt-square': u('\uf1e1'),
            'share-square': u('\uf14d'),
            'share-square-o': u('\uf045'),
            'shield': u('\uf132'),
            'shopping-cart': u('\uf07a'),
            'sign-in': u('\uf090'),
            'sign-out': u('\uf08b'),
            'signal': u('\uf012'),
            'sitemap': u('\uf0e8'),
            'skype': u('\uf17e'),
            'slack': u('\uf198'),
            'sliders': u('\uf1de'),
            'smile-o': u('\uf118'),
            'sort': u('\uf0dc'),
            'sort-alpha-asc': u('\uf15d'),
            'sort-alpha-desc': u('\uf15e'),
            'sort-amount-asc': u('\uf160'),
            'sort-amount-desc': u('\uf161'),
            'sort-asc': u('\uf0de'),
            'sort-desc': u('\uf0dd'),
            'sort-down': u('\uf0dd'),
            'sort-numeric-asc': u('\uf162'),
            'sort-numeric-desc': u('\uf163'),
            'sort-up': u('\uf0de'),
            'soundcloud': u('\uf1be'),
            'space-shuttle': u('\uf197'),
            'spinner': u('\uf110'),
            'spoon': u('\uf1b1'),
            'spotify': u('\uf1bc'),
            'square': u('\uf0c8'),
            'square-o': u('\uf096'),
            'stack-exchange': u('\uf18d'),
            'stack-overflow': u('\uf16c'),
            'star': u('\uf005'),
            'star-half': u('\uf089'),
            'star-half-empty': u('\uf123'),
            'star-half-full': u('\uf123'),
            'star-half-o': u('\uf123'),
            'star-o': u('\uf006'),
            'steam': u('\uf1b6'),
            'steam-square': u('\uf1b7'),
            'step-backward': u('\uf048'),
            'step-forward': u('\uf051'),
            'stethoscope': u('\uf0f1'),
            'stop': u('\uf04d'),
            'strikethrough': u('\uf0cc'),
            'stumbleupon': u('\uf1a4'),
            'stumbleupon-circle': u('\uf1a3'),
            'subscript': u('\uf12c'),
            'suitcase': u('\uf0f2'),
            'sun-o': u('\uf185'),
            'superscript': u('\uf12b'),
            'support': u('\uf1cd'),
            'table': u('\uf0ce'),
            'tablet': u('\uf10a'),
            'tachometer': u('\uf0e4'),
            'tag': u('\uf02b'),
            'tags': u('\uf02c'),
            'tasks': u('\uf0ae'),
            'taxi': u('\uf1ba'),
            'tencent-weibo': u('\uf1d5'),
            'terminal': u('\uf120'),
            'text-height': u('\uf034'),
            'text-width': u('\uf035'),
            'th': u('\uf00a'),
            'th-large': u('\uf009'),
            'th-list': u('\uf00b'),
            'thumb-tack': u('\uf08d'),
            'thumbs-down': u('\uf165'),
            'thumbs-o-down': u('\uf088'),
            'thumbs-o-up': u('\uf087'),
            'thumbs-up': u('\uf164'),
            'ticket': u('\uf145'),
            'times': u('\uf00d'),
            'times-circle': u('\uf057'),
            'times-circle-o': u('\uf05c'),
            'tint': u('\uf043'),
            'toggle-down': u('\uf150'),
            'toggle-left': u('\uf191'),
            'toggle-right': u('\uf152'),
            'toggle-up': u('\uf151'),
            'trash-o': u('\uf014'),
            'tree': u('\uf1bb'),
            'trello': u('\uf181'),
            'trophy': u('\uf091'),
            'truck': u('\uf0d1'),
            'try': u('\uf195'),
            'tumblr': u('\uf173'),
            'tumblr-square': u('\uf174'),
            'turkish-lira': u('\uf195'),
            'twitter': u('\uf099'),
            'twitter-square': u('\uf081'),
            'umbrella': u('\uf0e9'),
            'underline': u('\uf0cd'),
            'undo': u('\uf0e2'),
            'university': u('\uf19c'),
            'unlink': u('\uf127'),
            'unlock': u('\uf09c'),
            'unlock-alt': u('\uf13e'),
            'unsorted': u('\uf0dc'),
            'upload': u('\uf093'),
            'usd': u('\uf155'),
            'user': u('\uf007'),
            'user-md': u('\uf0f0'),
            'users': u('\uf0c0'),
            'video-camera': u('\uf03d'),
            'vimeo-square': u('\uf194'),
            'vine': u('\uf1ca'),
            'vk': u('\uf189'),
            'volume-down': u('\uf027'),
            'volume-off': u('\uf026'),
            'volume-up': u('\uf028'),
            'warning': u('\uf071'),
            'wechat': u('\uf1d7'),
            'weibo': u('\uf18a'),
            'weixin': u('\uf1d7'),
            'wheelchair': u('\uf193'),
            'windows': u('\uf17a'),
            'won': u('\uf159'),
            'wordpress': u('\uf19a'),
            'wrench': u('\uf0ad'),
            'xing': u('\uf168'),
            'xing-square': u('\uf169'),
            'yahoo': u('\uf19e'),
            'yen': u('\uf157'),
            'youtube': u('\uf167'),
            'youtube-play': u('\uf16a'),
            'youtube-square': u('\uf166')
        },
    },
    # 'entypo': {
    #     'name': 'Entypo',
    #     'ttf': 'Entypo.ttf',
    #     'credit': 'Daniel Bruce',
    #     'url': 'http://www.entypo.com/',
    #     'licence': 'http://creativecommons.org/licenses/by-sa/3.0/',
    #     # 'woff': 'fontawesome-webfont.woff',
    #     'css': 'entypo.css',
    #     'classgen': lambda s: 'entypo ' + s,
    #     'characters': {
    #         'add-to-list': u('\uE003'),
    #         'add-user': u('\uE700'),
    #         'address': u('\uE723'),
    #         'adjust': u('\u25D1'),
    #         'air': u('\u1F4A8'),
    #         'airplane': u('\u2708'),
    #         'archive': u('\uE800'),
    #         'area-graph': u('\u1F53E'),
    #         'arrow-combo': u('\uE74F'),
    #         'attach': u('\u1F4CE'),
    #         'back': u('\u1F519'),
    #         'back-in-time': u('\uE771'),
    #         'bag': u('\u1F45C'),
    #         'bar-graph': u('\u1F4CA'),
    #         'battery': u('\u1F50B'),
    #         'beamed-note': u('\u266B'),
    #         'bell': u('\u1F514'),
    #         'block': u('\u1F6AB'),
    #         'book': u('\u1F4D5'),
    #         'bookmark': u('\u1F516'),
    #         'bookmarks': u('\u1F4D1'),
    #         'box': u('\u1F4E6'),
    #         'briefcase': u('\u1F4BC'),
    #         'browser': u('\uE74E'),
    #         'brush': u('\uE79A'),
    #         'bucket': u('\u1F4FE'),
    #         'calendar': u('\u1F4C5'),
    #         'camera': u('\u1F4F7'),
    #         'cart': u('\uE73D'),
    #         'cc': u('\u1F545'),
    #         'cc-by': u('\u1F546'),
    #         'cc-nc': u('\u1F547'),
    #         'cc-nc-eu': u('\u1F548'),
    #         'cc-nc-jp': u('\u1F549'),
    #         'cc-nd': u('\u1F54B'),
    #         'cc-pd': u('\u1F54C'),
    #         'cc-remix': u('\u1F54F'),
    #         'cc-sa': u('\u1F54A'),
    #         'cc-share': u('\u1F54E'),
    #         'cc-zero': u('\u1F54D'),
    #         'ccw': u('\u27F2'),
    #         'cd': u('\u1F4BF'),
    #         'chat': u('\uE720'),
    #         'check': u('\u2713'),
    #         'chevron-down': u('\uE75C'),
    #         'chevron-left': u('\uE75D'),
    #         'chevron-right': u('\uE75E'),
    #         'chevron-small-down': u('\uE760'),
    #         'chevron-small-left': u('\uE761'),
    #         'chevron-small-right': u('\uE762'),
    #         'chevron-small-up': u('\uE763'),
    #         'chevron-thin-down': u('\uE764'),
    #         'chevron-thin-left': u('\uE765'),
    #         'chevron-thin-right': u('\uE766'),
    #         'chevron-thin-up': u('\uE767'),
    #         'chevron-up': u('\uE75F'),
    #         'circled-cross': u('\u2716'),
    #         'circled-down': u('\uE758'),
    #         'circled-help': u('\uE704'),
    #         'circled-info': u('\uE705'),
    #         'circled-left': u('\uE759'),
    #         'circled-minus': u('\u2296'),
    #         'circled-plus': u('\u2295'),
    #         'circled-right': u('\uE75A'),
    #         'circled-up': u('\uE75B'),
    #         'clipboard': u('\u1F4CB'),
    #         'clock': u('\u1F554'),
    #         'cloud': u('\u2601'),
    #         'code': u('\uE714'),
    #         'cog': u('\u2699'),
    #         'comment': u('\uE718'),
    #         'compass': u('\uE728'),
    #         'credit-card': u('\u1F4B3'),
    #         'cross': u('\u274C'),
    #         'cup': u('\u2615'),
    #         'cw': u('\u27F3'),
    #         'cycle': u('\u1F504'),
    #         'database': u('\u1F4F8'),
    #         'db-logo': u('\u1F5F9'),
    #         'db-shape': u('\u1F5FA'),
    #         'direction': u('\u27A2'),
    #         'doc': u('\uE730'),
    #         'docs': u('\uE736'),
    #         'dot': u('\u23F4'),
    #         'down': u('\u2B07'),
    #         'down-bold': u('\uE4B0'),
    #         'down-thin': u('\u2193'),
    #         'download': u('\u1F4E5'),
    #         'drive': u('\u1F4FD'),
    #         'droplet': u('\u1F4A7'),
    #         'erase': u('\u232B'),
    #         'export': u('\uE715'),
    #         'eye': u('\uE70A'),
    #         'fb': u('\u23EA'),
    #         'feather': u('\u2712'),
    #         'ff': u('\u23E9'),
    #         'flag': u('\u2691'),
    #         'flash': u('\u26A1'),
    #         'flashlight': u('\u1F526'),
    #         'flow-branch': u('\u1F569'),
    #         'flow-cascade': u('\u1F568'),
    #         'flow-line': u('\u1F56B'),
    #         'flow-parallel': u('\u1F56C'),
    #         'flow-tree': u('\u1F56A'),
    #         'folder': u('\u1F4C1'),
    #         'forward': u('\u27A6'),
    #         'gauge': u('\u1F6C7'),
    #         'globe': u('\u1F30E'),
    #         'graduation-cap': u('\u1F393'),
    #         'hair-cross': u('\u1F3AF'),
    #         'heart': u('\u2665'),
    #         'heart-empty': u('\u2661'),
    #         'help': u('\u2753'),
    #         'home': u('\u2302'),
    #         'hourglass': u('\u23F3'),
    #         'inbox': u('\uE777'),
    #         'infinity': u('\u221E'),
    #         'info': u('\u2139'),
    #         'install': u('\uE778'),
    #         'key': u('\u1F511'),
    #         'keyboard': u('\u2328'),
    #         'landscape-doc': u('\uE737'),
    #         'language': u('\u1F394'),
    #         'layout': u('\u268F'),
    #         'leaf': u('\u1F342'),
    #         'left': u('\u2B05'),
    #         'left-bold': u('\uE4AD'),
    #         'left-thin': u('\u2190'),
    #         'level-down': u('\u21B3'),
    #         'level-up': u('\u21B0'),
    #         'lifebuoy': u('\uE788'),
    #         'light-bulb': u('\u1F4A1'),
    #         'light-down': u('\u1F505'),
    #         'light-up': u('\u1F506'),
    #         'line-graph': u('\u1F4C8'),
    #         'link': u('\u1F517'),
    #         'list': u('\u2630'),
    #         'location': u('\uE724'),
    #         'lock': u('\u1F512'),
    #         'lock-open': u('\u1F513'),
    #         'login': u('\uE740'),
    #         'logout': u('\uE741'),
    #         'loop': u('\u1F501'),
    #         'magnet': u('\uE7A1'),
    #         'mail': u('\u2709'),
    #         'map': u('\uE727'),
    #         'megaphone': u('\u1F4E3'),
    #         'mic': u('\u1F3A4'),
    #         'minus': u('\u2796'),
    #         'mobile': u('\u1F4F1'),
    #         'monitor': u('\u1F4BB'),
    #         'moon': u('\u263D'),
    #         'mouse': u('\uE789'),
    #         'music': u('\u1F3B5'),
    #         'mute': u('\u1F507'),
    #         'network': u('\uE776'),
    #         'new': u('\u1F4A5'),
    #         'newspaper': u('\u1F4F0'),
    #         'note': u('\u266A'),
    #         'numbered-list': u('\uE005'),
    #         'open-book': u('\u1F4D6'),
    #         'palette': u('\u1F3A8'),
    #         'paper-plane': u('\u1F53F'),
    #         'paus': u('\u2016'),
    #         'pencil': u('\u270E'),
    #         'phone': u('\u1F4DE'),
    #         'picture': u('\u1F304'),
    #         'pie-chart': u('\u25F4'),
    #         'play': u('\u25B6'),
    #         'plus': u('\u2795'),
    #         'popup': u('\uE74C'),
    #         'print': u('\uE716'),
    #         'progress-0': u('\uE768'),
    #         'progress-1': u('\uE769'),
    #         'progress-2': u('\uE76A'),
    #         'progress-3': u('\uE76B'),
    #         'publish': u('\uE74D'),
    #         'quote': u('\u275E'),
    #         'record': u('\u25CF'),
    #         'reply': u('\uE712'),
    #         'reply-all': u('\uE713'),
    #         'resize-full': u('\uE744'),
    #         'resize-small': u('\uE746'),
    #         'retweet': u('\uE717'),
    #         'right': u('\u27A1'),
    #         'right-bold': u('\uE4AE'),
    #         'right-thin': u('\u2192'),
    #         'rocket': u('\u1F680'),
    #         'rss': u('\uE73A'),
    #         'save': u('\u1F4BE'),
    #         'search': u('\u1F50D'),
    #         'share': u('\uE73C'),
    #         'shareable': u('\uE73E'),
    #         'shuffle': u('\u1F500'),
    #         'signal': u('\u1F4F6'),
    #         'sound': u('\u1F50A'),
    #         'squared-cross': u('\u274E'),
    #         'squared-minus': u('\u229F'),
    #         'squared-plus': u('\u229E'),
    #         'star': u('\u2605'),
    #         'star-empty': u('\u2606'),
    #         'stop': u('\u25A0'),
    #         'suitcase': u('\u1F6C6'),
    #         'sweden': u('\uF601'),
    #         'switch': u('\u21C6'),
    #         'tag': u('\uE70C'),
    #         'text-doc': u('\u1F4C4'),
    #         'text-doc-inverted': u('\uE731'),
    #         'thermometer': u('\u1F4FF'),
    #         'three-dots': u('\u23F6'),
    #         'thumbs-down': u('\u1F44E'),
    #         'thumbs-up': u('\u1F44D'),
    #         'thunder-cloud': u('\u26C8'),
    #         'ticket': u('\u1F3AB'),
    #         'to-end': u('\u23ED'),
    #         'to-start': u('\u23EE'),
    #         'tools': u('\u2692'),
    #         'traffic-cone': u('\u1F6C8'),
    #         'trash': u('\uE729'),
    #         'triangle-down': u('\u25BE'),
    #         'triangle-left': u('\u25C2'),
    #         'triangle-right': u('\u25B8'),
    #         'triangle-up': u('\u25B4'),
    #         'trophy': u('\u1F3C6'),
    #         'two-dots': u('\u23F5'),
    #         'up': u('\u2B06'),
    #         'up-bold': u('\uE4AF'),
    #         'up-thin': u('\u2191'),
    #         'upload': u('\u1F4E4'),
    #         'upload-cloud': u('\uE711'),
    #         'user': u('\u1F464'),
    #         'users': u('\u1F465'),
    #         'vcard': u('\uE722'),
    #         'video': u('\u1F3AC'),
    #         'voicemail': u('\u2707'),
    #         'volume': u('\u23F7'),
    #         'warning': u('\u26A0'),
    #         'water': u('\u1F4A6')
    #     }
    # },
    # 'entypo-social': {
    #     'name': 'Entypo Social',
    #     'ttf': 'Entypo-Social.ttf',
    #     'credit': 'Daniel Bruce',
    #     'url': 'http://www.entypo.com/',
    #     'licence': 'http://creativecommons.org/licenses/by-sa/3.0/',
    #     # 'woff': 'fontawesome-webfont.woff',
    #     'css': 'entypo.css',
    #     'classgen': lambda s: 'entypo-social ' + s,
    #     'characters': {
    #         'behance': u('\uF34E'),
    #         'c-dribbble': u('\uF31C'),
    #         'c-facebook': u('\uF30D'),
    #         'c-flickr': u('\uF304'),
    #         'c-github': u('\uF301'),
    #         'c-google-plus': u('\uF310'),
    #         'c-lastfm': u('\uF322'),
    #         'c-linkedin': u('\uF319'),
    #         'c-pinterest': u('\uF313'),
    #         'c-rdio': u('\uF325'),
    #         'c-skype': u('\uF33A'),
    #         'c-spotify': u('\uF328'),
    #         'c-stumbleupon': u('\uF31F'),
    #         'c-tumblr': u('\uF316'),
    #         'c-twitter': u('\uF30A'),
    #         'c-vimeo': u('\uF307'),
    #         'dribbble': u('\uF31B'),
    #         'dropbox': u('\uF330'),
    #         'evernote': u('\uF333'),
    #         'facebook': u('\uF30C'),
    #         'flattr': u('\uF336'),
    #         'flickr': u('\uF303'),
    #         'github': u('\uF300'),
    #         'google-plus': u('\uF30F'),
    #         'google-circles': u('\uF351'),
    #         'instagram': u('\uF32D'),
    #         'lastfm': u('\uF321'),
    #         'linkedin': u('\uF318'),
    #         'mixi': u('\uF34B'),
    #         'paypal': u('\uF342'),
    #         'picasa': u('\uF345'),
    #         'pinterest': u('\uF312'),
    #         'qq': u('\uF32A'),
    #         'rdio': u('\uF324'),
    #         'renren': u('\uF33C'),
    #         's-facebook': u('\uF30E'),
    #         'sina-weibo': u('\uF33F'),
    #         'skype': u('\uF339'),
    #         'smashing': u('\uF357'),
    #         'soundcloud': u('\uF348'),
    #         'spotify': u('\uF327'),
    #         'stumbleupon': u('\uF31E'),
    #         'tumblr': u('\uF315'),
    #         'twitter': u('\uF309'),
    #         'vimeo': u('\uF306'),
    #         'vk': u('\uF354'),
    #     }
    # },
    'icomoon': {
        'name': 'IcoMoon',
        'ttf': 'icomoon.ttf',
        'credit': 'IcoMoon.io',
        'url': 'http://icomoon.io/',
        'licence': 'http://icomoon.io/#termsofuse',
        # 'woff': 'fontawesome-webfont.woff',
        'css': 'icomoon.css',
        'classgen': lambda s: 'icon-' + s,
        'characters': {
            'accessibility': u('\ue6ad'),
            'address-book': u('\ue63e'),
            'aid': u('\ue693'),
            'airplane': u('\ue6aa'),
            'alarm': u('\ue64a'),
            'alarm2': u('\ue64b'),
            'android': u('\ue798'),
            'angry': u('\ue6e4'),
            'angry2': u('\ue6e5'),
            'apple': u('\ue796'),
            'arrow-down': u('\ue724'),
            'arrow-down-left': u('\ue725'),
            'arrow-down-left2': u('\ue72d'),
            'arrow-down-left3': u('\ue735'),
            'arrow-down-right': u('\ue723'),
            'arrow-down-right2': u('\ue72b'),
            'arrow-down-right3': u('\ue733'),
            'arrow-down2': u('\ue72c'),
            'arrow-down3': u('\ue734'),
            'arrow-left': u('\ue726'),
            'arrow-left2': u('\ue72e'),
            'arrow-left3': u('\ue736'),
            'arrow-right': u('\ue722'),
            'arrow-right2': u('\ue72a'),
            'arrow-right3': u('\ue732'),
            'arrow-up': u('\ue720'),
            'arrow-up-left': u('\ue71f'),
            'arrow-up-left2': u('\ue727'),
            'arrow-up-left3': u('\ue72f'),
            'arrow-up-right': u('\ue721'),
            'arrow-up-right2': u('\ue729'),
            'arrow-up-right3': u('\ue731'),
            'arrow-up2': u('\ue728'),
            'arrow-up3': u('\ue730'),
            'attachment': u('\ue6c5'),
            'backward': u('\ue708'),
            'backward2': u('\ue70d'),
            'barcode': u('\ue632'),
            'bars': u('\ue697'),
            'bars2': u('\ue698'),
            'bell': u('\ue64c'),
            'binoculars': u('\ue67e'),
            'blocked': u('\ue6f9'),
            'blog': u('\ue609'),
            'blogger': u('\ue790'),
            'blogger2': u('\ue791'),
            'bold': u('\ue744'),
            'book': u('\ue61f'),
            'bookmark': u('\ue6c9'),
            'bookmarks': u('\ue6ca'),
            'books': u('\ue620'),
            'box-add': u('\ue65c'),
            'box-remove': u('\ue65d'),
            'briefcase': u('\ue6a9'),
            'brightness-contrast': u('\ue6cc'),
            'brightness-medium': u('\ue6cb'),
            'bubble': u('\ue66a'),
            'bubble2': u('\ue66d'),
            'bubbles': u('\ue66b'),
            'bubbles2': u('\ue66c'),
            'bubbles3': u('\ue66e'),
            'bubbles4': u('\ue66f'),
            'bug': u('\ue694'),
            'bullhorn': u('\ue61b'),
            'busy': u('\ue677'),
            'cabinet': u('\ue658'),
            'calculate': u('\ue63a'),
            'calendar': u('\ue64e'),
            'calendar2': u('\ue64f'),
            'camera': u('\ue60f'),
            'camera2': u('\ue614'),
            'cancel-circle': u('\ue6fa'),
            'cart': u('\ue635'),
            'cart2': u('\ue636'),
            'cart3': u('\ue637'),
            'checkbox-checked': u('\ue738'),
            'checkbox-partial': u('\ue73a'),
            'checkbox-unchecked': u('\ue739'),
            'checkmark': u('\ue6fe'),
            'checkmark-circle': u('\ue6fb'),
            'checkmark2': u('\ue6ff'),
            'chrome': u('\ue7bd'),
            'clock': u('\ue648'),
            'clock2': u('\ue649'),
            'close': u('\ue6fd'),
            'cloud': u('\ue6ba'),
            'cloud-download': u('\ue6bb'),
            'cloud-upload': u('\ue6bc'),
            'clubs': u('\ue618'),
            'code': u('\ue75c'),
            'cog': u('\ue68e'),
            'cog2': u('\ue690'),
            'cogs': u('\ue68f'),
            'coin': u('\ue638'),
            'compass': u('\ue644'),
            'confused': u('\ue6ea'),
            'confused2': u('\ue6eb'),
            'connection': u('\ue61c'),
            'console': u('\ue75d'),
            'contract': u('\ue683'),
            'contract2': u('\ue685'),
            'contrast': u('\ue6cd'),
            'cool': u('\ue6e2'),
            'cool2': u('\ue6e3'),
            'copy': u('\ue627'),
            'copy2': u('\ue628'),
            'copy3': u('\ue629'),
            'credit': u('\ue639'),
            'crop': u('\ue73d'),
            'css3': u('\ue7bc'),
            'dashboard': u('\ue6a2'),
            'delicious': u('\ue7a2'),
            'deviantart': u('\ue784'),
            'deviantart2': u('\ue785'),
            'diamonds': u('\ue619'),
            'dice': u('\ue615'),
            'disk': u('\ue660'),
            'download': u('\ue65e'),
            'download2': u('\ue6bd'),
            'download3': u('\ue6bf'),
            'drawer': u('\ue659'),
            'drawer2': u('\ue65a'),
            'drawer3': u('\ue65b'),
            'dribbble': u('\ue77f'),
            'dribbble2': u('\ue780'),
            'dribbble3': u('\ue781'),
            'droplet': u('\ue60a'),
            'earth': u('\ue6c2'),
            'eject': u('\ue713'),
            'embed': u('\ue75b'),
            'enter': u('\ue703'),
            'envelope': u('\ue640'),
            'equalizer': u('\ue68d'),
            'evil': u('\ue6e6'),
            'evil2': u('\ue6e7'),
            'exit': u('\ue704'),
            'expand': u('\ue682'),
            'expand2': u('\ue684'),
            'eye': u('\ue6c6'),
            'eye-blocked': u('\ue6c7'),
            'eye2': u('\ue6c8'),
            'facebook': u('\ue769'),
            'facebook2': u('\ue76a'),
            'facebook3': u('\ue76b'),
            'feed': u('\ue61e'),
            'feed2': u('\ue770'),
            'feed3': u('\ue771'),
            'feed4': u('\ue772'),
            'file': u('\ue622'),
            'file-css': u('\ue7b9'),
            'file-excel': u('\ue7b5'),
            'file-openoffice': u('\ue7b3'),
            'file-pdf': u('\ue7b2'),
            'file-powerpoint': u('\ue7b7'),
            'file-word': u('\ue7b4'),
            'file-xml': u('\ue7b8'),
            'file-zip': u('\ue7b6'),
            'file2': u('\ue624'),
            'file3': u('\ue625'),
            'file4': u('\ue626'),
            'film': u('\ue613'),
            'filter': u('\ue73f'),
            'filter2': u('\ue740'),
            'finder': u('\ue797'),
            'fire': u('\ue6a4'),
            'firefox': u('\ue7be'),
            'first': u('\ue70f'),
            'flag': u('\ue6c4'),
            'flattr': u('\ue7aa'),
            'flickr': u('\ue779'),
            'flickr2': u('\ue77a'),
            'flickr3': u('\ue77b'),
            'flickr4': u('\ue77c'),
            'flip': u('\ue664'),
            'flip2': u('\ue665'),
            'folder': u('\ue62e'),
            'folder-open': u('\ue62f'),
            'font': u('\ue741'),
            'food': u('\ue69d'),
            'forrst': u('\ue782'),
            'forrst2': u('\ue783'),
            'forward': u('\ue668'),
            'forward2': u('\ue709'),
            'forward3': u('\ue70e'),
            'foursquare': u('\ue7ab'),
            'foursquare2': u('\ue7ac'),
            'gift': u('\ue699'),
            'github': u('\ue788'),
            'github2': u('\ue789'),
            'github3': u('\ue78a'),
            'github4': u('\ue78b'),
            'github5': u('\ue78c'),
            'glass': u('\ue69b'),
            'globe': u('\ue6c1'),
            'google': u('\ue763'),
            'google-drive': u('\ue768'),
            'googleplus': u('\ue764'),
            'googleplus2': u('\ue765'),
            'googleplus3': u('\ue766'),
            'googleplus4': u('\ue767'),
            'grin': u('\ue6e0'),
            'grin2': u('\ue6e1'),
            'hammer': u('\ue691'),
            'hammer2': u('\ue6a3'),
            'happy': u('\ue6d6'),
            'happy2': u('\ue6d7'),
            'headphones': u('\ue611'),
            'heart': u('\ue6d1'),
            'heart-broken': u('\ue6d3'),
            'heart2': u('\ue6d2'),
            'history': u('\ue647'),
            'home': u('\ue600'),
            'home2': u('\ue601'),
            'home3': u('\ue602'),
            'html5': u('\ue7ba'),
            'html52': u('\ue7bb'),
            'icomoon': u('\ue7c2'),
            'ie': u('\ue7bf'),
            'image': u('\ue60c'),
            'image2': u('\ue60d'),
            'images': u('\ue60e'),
            'indent-decrease': u('\ue759'),
            'indent-increase': u('\ue758'),
            'info': u('\ue6f7'),
            'info2': u('\ue6f8'),
            'insert-template': u('\ue74c'),
            'instagram': u('\ue76c'),
            'italic': u('\ue746'),
            'joomla': u('\ue78f'),
            'key': u('\ue686'),
            'key2': u('\ue687'),
            'keyboard': u('\ue651'),
            'lab': u('\ue6a5'),
            'lanyrd': u('\ue778'),
            'laptop': u('\ue653'),
            'last': u('\ue710'),
            'lastfm': u('\ue7a0'),
            'lastfm2': u('\ue7a1'),
            'leaf': u('\ue69e'),
            'lefttoright': u('\ue74e'),
            'library': u('\ue621'),
            'libreoffice': u('\ue7b1'),
            'lightning': u('\ue6b0'),
            'link': u('\ue6c3'),
            'linkedin': u('\ue79f'),
            'list': u('\ue6b4'),
            'list2': u('\ue6b5'),
            'location': u('\ue642'),
            'location2': u('\ue643'),
            'lock': u('\ue688'),
            'lock2': u('\ue689'),
            'loop': u('\ue71b'),
            'loop2': u('\ue71c'),
            'loop3': u('\ue71d'),
            'magnet': u('\ue6a6'),
            'mail': u('\ue75f'),
            'mail2': u('\ue760'),
            'mail3': u('\ue761'),
            'mail4': u('\ue762'),
            'map': u('\ue645'),
            'map2': u('\ue646'),
            'menu': u('\ue6b7'),
            'menu2': u('\ue6b8'),
            'meter': u('\ue6a0'),
            'meter2': u('\ue6a1'),
            'minus': u('\ue701'),
            'mobile': u('\ue654'),
            'mobile2': u('\ue655'),
            'mug': u('\ue69c'),
            'music': u('\ue610'),
            'neutral': u('\ue6ec'),
            'neutral2': u('\ue6ed'),
            'newspaper': u('\ue604'),
            'newtab': u('\ue75a'),
            'next': u('\ue712'),
            'notebook': u('\ue63f'),
            'notification': u('\ue6f5'),
            'numbered-list': u('\ue6b6'),
            'office': u('\ue603'),
            'omega': u('\ue748'),
            'opera': u('\ue7c0'),
            'pacman': u('\ue616'),
            'paint-format': u('\ue60b'),
            'paragraph-center': u('\ue751'),
            'paragraph-center2': u('\ue755'),
            'paragraph-justify': u('\ue753'),
            'paragraph-justify2': u('\ue757'),
            'paragraph-left': u('\ue750'),
            'paragraph-left2': u('\ue754'),
            'paragraph-right': u('\ue752'),
            'paragraph-right2': u('\ue756'),
            'paste': u('\ue62a'),
            'paste2': u('\ue62b'),
            'paste3': u('\ue62c'),
            'pause': u('\ue706'),
            'pause2': u('\ue70b'),
            'pawn': u('\ue61a'),
            'paypal': u('\ue7ad'),
            'paypal2': u('\ue7ae'),
            'paypal3': u('\ue7af'),
            'pen': u('\ue608'),
            'pencil': u('\ue605'),
            'pencil2': u('\ue606'),
            'phone': u('\ue63c'),
            'phone-hang-up': u('\ue63d'),
            'picassa': u('\ue77d'),
            'picassa2': u('\ue77e'),
            'pie': u('\ue695'),
            'pilcrow': u('\ue74d'),
            'pinterest': u('\ue7a6'),
            'pinterest2': u('\ue7a7'),
            'play': u('\ue612'),
            'play2': u('\ue705'),
            'play3': u('\ue70a'),
            'plus': u('\ue702'),
            'podcast': u('\ue61d'),
            'point-down': u('\ue6f2'),
            'point-left': u('\ue6f3'),
            'point-right': u('\ue6f1'),
            'point-up': u('\ue6f0'),
            'powercord': u('\ue6b2'),
            'previous': u('\ue711'),
            'print': u('\ue650'),
            'profile': u('\ue623'),
            'pushpin': u('\ue641'),
            'qrcode': u('\ue633'),
            'question': u('\ue6f6'),
            'quill': u('\ue607'),
            'quotes-left': u('\ue676'),
            'radio-checked': u('\ue73b'),
            'radio-unchecked': u('\ue73c'),
            'reddit': u('\ue79e'),
            'redo': u('\ue663'),
            'redo2': u('\ue667'),
            'remove': u('\ue6a7'),
            'remove2': u('\ue6a8'),
            'reply': u('\ue669'),
            'righttoleft': u('\ue74f'),
            'road': u('\ue6ac'),
            'rocket': u('\ue69f'),
            'sad': u('\ue6dc'),
            'sad2': u('\ue6dd'),
            'safari': u('\ue7c1'),
            'scissors': u('\ue73e'),
            'screen': u('\ue652'),
            'search': u('\ue67f'),
            'settings': u('\ue68c'),
            'share': u('\ue75e'),
            'shield': u('\ue6af'),
            'shocked': u('\ue6e8'),
            'shocked2': u('\ue6e9'),
            'shuffle': u('\ue71e'),
            'sigma': u('\ue749'),
            'signup': u('\ue6b3'),
            'skype': u('\ue79d'),
            'smiley': u('\ue6d8'),
            'smiley2': u('\ue6d9'),
            'soundcloud': u('\ue79b'),
            'soundcloud2': u('\ue79c'),
            'spades': u('\ue617'),
            'spam': u('\ue6fc'),
            'spell-check': u('\ue700'),
            'spinner': u('\ue678'),
            'spinner2': u('\ue679'),
            'spinner3': u('\ue67a'),
            'spinner4': u('\ue67b'),
            'spinner5': u('\ue67c'),
            'spinner6': u('\ue67d'),
            'stack': u('\ue62d'),
            'stackoverflow': u('\ue7a5'),
            'star': u('\ue6ce'),
            'star2': u('\ue6cf'),
            'star3': u('\ue6d0'),
            'stats': u('\ue696'),
            'steam': u('\ue786'),
            'steam2': u('\ue787'),
            'stop': u('\ue707'),
            'stop2': u('\ue70c'),
            'stopwatch': u('\ue64d'),
            'storage': u('\ue661'),
            'strikethrough': u('\ue747'),
            'stumbleupon': u('\ue7a3'),
            'stumbleupon2': u('\ue7a4'),
            'support': u('\ue63b'),
            'switch': u('\ue6b1'),
            'tab': u('\ue737'),
            'table': u('\ue74a'),
            'table2': u('\ue74b'),
            'tablet': u('\ue656'),
            'tag': u('\ue630'),
            'tags': u('\ue631'),
            'target': u('\ue6ae'),
            'text-height': u('\ue742'),
            'text-width': u('\ue743'),
            'thumbs-up': u('\ue6d4'),
            'thumbs-up2': u('\ue6d5'),
            'ticket': u('\ue634'),
            'tongue': u('\ue6da'),
            'tongue2': u('\ue6db'),
            'tree': u('\ue6b9'),
            'trophy': u('\ue69a'),
            'truck': u('\ue6ab'),
            'tumblr': u('\ue792'),
            'tumblr2': u('\ue793'),
            'tux': u('\ue795'),
            'tv': u('\ue657'),
            'twitter': u('\ue76d'),
            'twitter2': u('\ue76e'),
            'twitter3': u('\ue76f'),
            'underline': u('\ue745'),
            'undo': u('\ue662'),
            'undo2': u('\ue666'),
            'unlocked': u('\ue68a'),
            'upload': u('\ue65f'),
            'upload2': u('\ue6be'),
            'upload3': u('\ue6c0'),
            'user': u('\ue670'),
            'user2': u('\ue672'),
            'user3': u('\ue674'),
            'user4': u('\ue675'),
            'users': u('\ue671'),
            'users2': u('\ue673'),
            'vimeo': u('\ue775'),
            'vimeo2': u('\ue776'),
            'vimeo3': u('\ue777'),
            'volume-decrease': u('\ue71a'),
            'volume-high': u('\ue714'),
            'volume-increase': u('\ue719'),
            'volume-low': u('\ue716'),
            'volume-medium': u('\ue715'),
            'volume-mute': u('\ue717'),
            'volume-mute2': u('\ue718'),
            'wand': u('\ue692'),
            'warning': u('\ue6f4'),
            'windows': u('\ue799'),
            'windows8': u('\ue79a'),
            'wink': u('\ue6de'),
            'wink2': u('\ue6df'),
            'wondering': u('\ue6ee'),
            'wondering2': u('\ue6ef'),
            'wordpress': u('\ue78d'),
            'wordpress2': u('\ue78e'),
            'wrench': u('\ue68b'),
            'xing': u('\ue7a8'),
            'xing2': u('\ue7a9'),
            'yahoo': u('\ue794'),
            'yelp': u('\ue7b0'),
            'youtube': u('\ue773'),
            'youtube2': u('\ue774'),
            'zoomin': u('\ue680'),
            'zoomout': u('\ue681'),
        }
    },
    'typicons': {
        'name': 'Typicons',
        'ttf': 'typicons.ttf',
        'credit': 'Stephen Hutchings',
        'url': 'http://typicons.com/',
        'licence': 'http://scripts.sil.org/OFL',
        # 'woff': 'fontawesome-webfont.woff',
        'css': 'typicons.css',
        'classgen': lambda s: 'typcn typcn-' + s,
        'characters': {
            'adjust-brightness': u('\ue000'),
            'adjust-contrast': u('\ue001'),
            'anchor': u('\ue003'),
            'anchor-outline': u('\ue002'),
            'archive': u('\ue004'),
            'arrow-back': u('\ue006'),
            'arrow-back-outline': u('\ue005'),
            'arrow-down': u('\ue009'),
            'arrow-down-outline': u('\ue007'),
            'arrow-down-thick': u('\ue008'),
            'arrow-forward': u('\ue00b'),
            'arrow-forward-outline': u('\ue00a'),
            'arrow-left': u('\ue00e'),
            'arrow-left-outline': u('\ue00c'),
            'arrow-left-thick': u('\ue00d'),
            'arrow-loop': u('\ue010'),
            'arrow-loop-outline': u('\ue00f'),
            'arrow-maximise': u('\ue012'),
            'arrow-maximise-outline': u('\ue011'),
            'arrow-minimise': u('\ue014'),
            'arrow-minimise-outline': u('\ue013'),
            'arrow-move': u('\ue016'),
            'arrow-move-outline': u('\ue015'),
            'arrow-repeat': u('\ue018'),
            'arrow-repeat-outline': u('\ue017'),
            'arrow-right': u('\ue01b'),
            'arrow-right-outline': u('\ue019'),
            'arrow-right-thick': u('\ue01a'),
            'arrow-shuffle': u('\ue01c'),
            'arrow-sorted-down': u('\ue01d'),
            'arrow-sorted-up': u('\ue01e'),
            'arrow-sync': u('\ue020'),
            'arrow-sync-outline': u('\ue01f'),
            'arrow-unsorted': u('\ue021'),
            'arrow-up': u('\ue024'),
            'arrow-up-outline': u('\ue022'),
            'arrow-up-thick': u('\ue023'),
            'at': u('\ue025'),
            'attachment': u('\ue027'),
            'attachment-outline': u('\ue026'),
            'backspace': u('\ue029'),
            'backspace-outline': u('\ue028'),
            'battery-charge': u('\ue02a'),
            'battery-full': u('\ue02b'),
            'battery-high': u('\ue02c'),
            'battery-low': u('\ue02d'),
            'battery-mid': u('\ue02e'),
            'beaker': u('\ue02f'),
            'beer': u('\ue030'),
            'bell': u('\ue031'),
            'book': u('\ue032'),
            'bookmark': u('\ue033'),
            'briefcase': u('\ue034'),
            'brush': u('\ue035'),
            'business-card': u('\ue036'),
            'calculator': u('\ue037'),
            'calender': u('\ue039'),
            'calender-outline': u('\ue038'),
            'camera': u('\ue03b'),
            'camera-outline': u('\ue03a'),
            'cancel': u('\ue03d'),
            'cancel-outline': u('\ue03c'),
            'chart-area': u('\ue03f'),
            'chart-area-outline': u('\ue03e'),
            'chart-bar': u('\ue041'),
            'chart-bar-outline': u('\ue040'),
            'chart-line': u('\ue043'),
            'chart-line-outline': u('\ue042'),
            'chart-pie': u('\ue045'),
            'chart-pie-outline': u('\ue044'),
            'chevron-left': u('\ue047'),
            'chevron-left-outline': u('\ue046'),
            'chevron-right': u('\ue049'),
            'chevron-right-outline': u('\ue048'),
            'clipboard': u('\ue04a'),
            'cloud-storage': u('\ue04b'),
            'code': u('\ue04d'),
            'code-outline': u('\ue04c'),
            'coffee': u('\ue04e'),
            'cog': u('\ue050'),
            'cog-outline': u('\ue04f'),
            'compass': u('\ue051'),
            'contacts': u('\ue052'),
            'credit-card': u('\ue053'),
            'cross': u('\ue054'),
            'css3': u('\ue055'),
            'database': u('\ue056'),
            'delete': u('\ue058'),
            'delete-outline': u('\ue057'),
            'device-desktop': u('\ue059'),
            'device-laptop': u('\ue05a'),
            'device-phone': u('\ue05b'),
            'device-tablet': u('\ue05c'),
            'directions': u('\ue05d'),
            'divide': u('\ue05f'),
            'divide-outline': u('\ue05e'),
            'document': u('\ue063'),
            'document-add': u('\ue060'),
            'document-delete': u('\ue061'),
            'document-text': u('\ue062'),
            'download': u('\ue065'),
            'download-outline': u('\ue064'),
            'dropbox': u('\ue066'),
            'edit': u('\ue067'),
            'eject': u('\ue069'),
            'eject-outline': u('\ue068'),
            'equals': u('\ue06b'),
            'equals-outline': u('\ue06a'),
            'export': u('\ue06d'),
            'export-outline': u('\ue06c'),
            'eye': u('\ue06f'),
            'eye-outline': u('\ue06e'),
            'feather': u('\ue070'),
            'film': u('\ue071'),
            'filter': u('\ue072'),
            'flag': u('\ue074'),
            'flag-outline': u('\ue073'),
            'flash': u('\ue076'),
            'flash-outline': u('\ue075'),
            'flow-children': u('\ue077'),
            'flow-merge': u('\ue078'),
            'flow-parallel': u('\ue079'),
            'flow-switch': u('\ue07a'),
            'folder': u('\ue07e'),
            'folder-add': u('\ue07b'),
            'folder-delete': u('\ue07c'),
            'folder-open': u('\ue07d'),
            'gift': u('\ue07f'),
            'globe': u('\ue081'),
            'globe-outline': u('\ue080'),
            'group': u('\ue083'),
            'group-outline': u('\ue082'),
            'headphones': u('\ue084'),
            'heart': u('\ue088'),
            'heart-full-outline': u('\ue085'),
            'heart-half-outline': u('\ue086'),
            'heart-outline': u('\ue087'),
            'home': u('\ue08a'),
            'home-outline': u('\ue089'),
            'html5': u('\ue08b'),
            'image': u('\ue08d'),
            'image-outline': u('\ue08c'),
            'infinity': u('\ue08f'),
            'infinity-outline': u('\ue08e'),
            'info': u('\ue093'),
            'info-large': u('\ue091'),
            'info-large-outline': u('\ue090'),
            'info-outline': u('\ue092'),
            'input-checked': u('\ue095'),
            'input-checked-outline': u('\ue094'),
            'key': u('\ue097'),
            'key-outline': u('\ue096'),
            'keyboard': u('\ue098'),
            'leaf': u('\ue099'),
            'lightbulb': u('\ue09a'),
            'link': u('\ue09c'),
            'link-outline': u('\ue09b'),
            'location': u('\ue0a0'),
            'location-arrow': u('\ue09e'),
            'location-arrow-outline': u('\ue09d'),
            'location-outline': u('\ue09f'),
            'lock-closed': u('\ue0a2'),
            'lock-closed-outline': u('\ue0a1'),
            'lock-open': u('\ue0a4'),
            'lock-open-outline': u('\ue0a3'),
            'mail': u('\ue0a5'),
            'map': u('\ue0a6'),
            'media-eject': u('\ue0a8'),
            'media-eject-outline': u('\ue0a7'),
            'media-fast-forward': u('\ue0aa'),
            'media-fast-forward-outline': u('\ue0a9'),
            'media-pause': u('\ue0ac'),
            'media-pause-outline': u('\ue0ab'),
            'media-play': u('\ue0b0'),
            'media-play-outline': u('\ue0ad'),
            'media-play-reverse': u('\ue0af'),
            'media-play-reverse-outline': u('\ue0ae'),
            'media-record': u('\ue0b2'),
            'media-record-outline': u('\ue0b1'),
            'media-rewind': u('\ue0b4'),
            'media-rewind-outline': u('\ue0b3'),
            'media-stop': u('\ue0b6'),
            'media-stop-outline': u('\ue0b5'),
            'message': u('\ue0b8'),
            'message-typing': u('\ue0b7'),
            'messages': u('\ue0b9'),
            'microphone': u('\ue0bb'),
            'microphone-outline': u('\ue0ba'),
            'minus': u('\ue0bd'),
            'minus-outline': u('\ue0bc'),
            'mortar-board': u('\ue0be'),
            'news': u('\ue0bf'),
            'notes': u('\ue0c1'),
            'notes-outline': u('\ue0c0'),
            'pen': u('\ue0c2'),
            'pencil': u('\ue0c3'),
            'phone': u('\ue0c5'),
            'phone-outline': u('\ue0c4'),
            'pi': u('\ue0c7'),
            'pi-outline': u('\ue0c6'),
            'pin': u('\ue0c9'),
            'pin-outline': u('\ue0c8'),
            'pipette': u('\ue0ca'),
            'plane': u('\ue0cc'),
            'plane-outline': u('\ue0cb'),
            'plug': u('\ue0cd'),
            'plus': u('\ue0cf'),
            'plus-outline': u('\ue0ce'),
            'point-of-interest': u('\ue0d1'),
            'point-of-interest-outline': u('\ue0d0'),
            'power': u('\ue0d3'),
            'power-outline': u('\ue0d2'),
            'printer': u('\ue0d4'),
            'puzzle': u('\ue0d6'),
            'puzzle-outline': u('\ue0d5'),
            'radar': u('\ue0d8'),
            'radar-outline': u('\ue0d7'),
            'refresh': u('\ue0da'),
            'refresh-outline': u('\ue0d9'),
            'rss': u('\ue0dc'),
            'rss-outline': u('\ue0db'),
            'scissors': u('\ue0de'),
            'scissors-outline': u('\ue0dd'),
            'shopping-bag': u('\ue0df'),
            'shopping-cart': u('\ue0e0'),
            'social-at-circular': u('\ue0e1'),
            'social-dribbble': u('\ue0e3'),
            'social-dribbble-circular': u('\ue0e2'),
            'social-facebook': u('\ue0e5'),
            'social-facebook-circular': u('\ue0e4'),
            'social-flickr': u('\ue0e7'),
            'social-flickr-circular': u('\ue0e6'),
            'social-github': u('\ue0e9'),
            'social-github-circular': u('\ue0e8'),
            'social-google-plus': u('\ue0eb'),
            'social-google-plus-circular': u('\ue0ea'),
            'social-instagram': u('\ue0ed'),
            'social-instagram-circular': u('\ue0ec'),
            'social-last-fm': u('\ue0ef'),
            'social-last-fm-circular': u('\ue0ee'),
            'social-linkedin': u('\ue0f1'),
            'social-linkedin-circular': u('\ue0f0'),
            'social-pinterest': u('\ue0f3'),
            'social-pinterest-circular': u('\ue0f2'),
            'social-skype': u('\ue0f5'),
            'social-skype-outline': u('\ue0f4'),
            'social-tumbler': u('\ue0f7'),
            'social-tumbler-circular': u('\ue0f6'),
            'social-twitter': u('\ue0f9'),
            'social-twitter-circular': u('\ue0f8'),
            'social-vimeo': u('\ue0fb'),
            'social-vimeo-circular': u('\ue0fa'),
            'social-youtube': u('\ue0fd'),
            'social-youtube-circular': u('\ue0fc'),
            'sort-alphabetically': u('\ue0ff'),
            'sort-alphabetically-outline': u('\ue0fe'),
            'sort-numerically': u('\ue101'),
            'sort-numerically-outline': u('\ue100'),
            'spanner': u('\ue103'),
            'spanner-outline': u('\ue102'),
            'spiral': u('\ue104'),
            'star': u('\ue109'),
            'star-full-outline': u('\ue105'),
            'star-half': u('\ue107'),
            'star-half-outline': u('\ue106'),
            'star-outline': u('\ue108'),
            'starburst': u('\ue10b'),
            'starburst-outline': u('\ue10a'),
            'stopwatch': u('\ue10c'),
            'support': u('\ue10d'),
            'tabs-outline': u('\ue10e'),
            'tag': u('\ue10f'),
            'tags': u('\ue110'),
            'th-large': u('\ue112'),
            'th-large-outline': u('\ue111'),
            'th-list': u('\ue114'),
            'th-list-outline': u('\ue113'),
            'th-menu': u('\ue116'),
            'th-menu-outline': u('\ue115'),
            'th-small': u('\ue118'),
            'th-small-outline': u('\ue117'),
            'thermometer': u('\ue119'),
            'thumbs-down': u('\ue11a'),
            'thumbs-ok': u('\ue11b'),
            'thumbs-up': u('\ue11c'),
            'tick': u('\ue11e'),
            'tick-outline': u('\ue11d'),
            'ticket': u('\ue11f'),
            'time': u('\ue120'),
            'times': u('\ue122'),
            'times-outline': u('\ue121'),
            'trash': u('\ue123'),
            'tree': u('\ue124'),
            'upload': u('\ue126'),
            'upload-outline': u('\ue125'),
            'user': u('\ue12c'),
            'user-add': u('\ue128'),
            'user-add-outline': u('\ue127'),
            'user-delete': u('\ue12a'),
            'user-delete-outline': u('\ue129'),
            'user-outline': u('\ue12b'),
            'vendor-android': u('\ue12d'),
            'vendor-apple': u('\ue12e'),
            'vendor-microsoft': u('\ue12f'),
            'video': u('\ue131'),
            'video-outline': u('\ue130'),
            'volume': u('\ue135'),
            'volume-down': u('\ue132'),
            'volume-mute': u('\ue133'),
            'volume-up': u('\ue134'),
            'warning': u('\ue137'),
            'warning-outline': u('\ue136'),
            'watch': u('\ue138'),
            'waves': u('\ue13a'),
            'waves-outline': u('\ue139'),
            'weather-cloudy': u('\ue13b'),
            'weather-downpour': u('\ue13c'),
            'weather-night': u('\ue13d'),
            'weather-partly-sunny': u('\ue13e'),
            'weather-shower': u('\ue13f'),
            'weather-snow': u('\ue140'),
            'weather-stormy': u('\ue141'),
            'weather-sunny': u('\ue142'),
            'weather-windy': u('\ue144'),
            'weather-windy-cloudy': u('\ue143'),
            'wi-fi': u('\ue146'),
            'wi-fi-outline': u('\ue145'),
            'wine': u('\ue147'),
            'world': u('\ue149'),
            'world-outline': u('\ue148'),
            'zoom': u('\ue14f'),
            'zoom-in': u('\ue14b'),
            'zoom-in-outline': u('\ue14a'),
            'zoom-out': u('\ue14d'),
            'zoom-out-outline': u('\ue14c'),
            'zoom-outline': u('\ue14e'),
        }
    },
    'elusive': {
        'name': 'Elusive Icons',
        'ttf': 'Elusive-Icons.ttf',
        'credit': 'Aristeides Stathopoulos',
        'url': 'https://github.com/aristath/elusive-iconfont',
        'licence': 'http://scripts.sil.org/OFL',
        # 'woff': 'fontawesome-webfont.woff',
        'css': 'elusive.css',
        'classgen': lambda s: 'el-icon-' + s,
        'characters': {
            'address-book': u('\ue729'),
            'address-book-alt': u('\ue728'),
            'adjust': u('\ue727'),
            'adjust-alt': u('\ue726'),
            'adult': u('\ue725'),
            'align-center': u('\ue724'),
            'align-justify': u('\ue723'),
            'align-left': u('\ue722'),
            'align-right': u('\ue721'),
            'arrow-down': u('\ue720'),
            'arrow-left': u('\ue71f'),
            'arrow-right': u('\ue71e'),
            'arrow-up': u('\ue71d'),
            'asl': u('\ue71c'),
            'asterisk': u('\ue72a'),
            'backward': u('\ue71b'),
            'ban-circle': u('\ue71a'),
            'barcode': u('\ue719'),
            'behance': u('\ue718'),
            'bell': u('\ue717'),
            'blind': u('\ue716'),
            'blogger': u('\ue715'),
            'bold': u('\ue714'),
            'book': u('\ue713'),
            'bookmark': u('\ue712'),
            'bookmark-empty': u('\ue711'),
            'braille': u('\ue710'),
            'briefcase': u('\ue70f'),
            'broom': u('\ue70e'),
            'brush': u('\ue70d'),
            'bulb': u('\ue70c'),
            'bullhorn': u('\ue70b'),
            'calendar': u('\ue70a'),
            'calendar-sign': u('\ue709'),
            'camera': u('\ue708'),
            'car': u('\ue707'),
            'caret-down': u('\ue706'),
            'caret-left': u('\ue705'),
            'caret-right': u('\ue704'),
            'caret-up': u('\ue703'),
            'cc': u('\ue702'),
            'certificate': u('\ue701'),
            'check': u('\ue700'),
            'check-empty': u('\ue6ff'),
            'chevron-down': u('\ue6fe'),
            'chevron-left': u('\ue6fd'),
            'chevron-right': u('\ue6fc'),
            'chevron-up': u('\ue6fb'),
            'child': u('\ue6fa'),
            'circle-arrow-down': u('\ue6f9'),
            'circle-arrow-left': u('\ue6f8'),
            'circle-arrow-right': u('\ue6f7'),
            'circle-arrow-up': u('\ue6f6'),
            'cloud': u('\ue6f5'),
            'cloud-alt': u('\ue6f4'),
            'cog': u('\ue6f3'),
            'cog-alt': u('\ue6f2'),
            'cogs': u('\ue6f1'),
            'comment': u('\ue6f0'),
            'comment-alt': u('\ue6ef'),
            'compass': u('\ue6ee'),
            'compass-alt': u('\ue6ed'),
            'credit-card': u('\ue6ec'),
            'css': u('\ue6eb'),
            'dashboard': u('\ue6ea'),
            'delicious': u('\ue6e9'),
            'deviantart': u('\ue6e8'),
            'digg': u('\ue6e7'),
            'download': u('\ue6e6'),
            'download-alt': u('\ue6e5'),
            'dribbble': u('\ue6e4'),
            'edit': u('\ue6e3'),
            'eject': u('\ue6e2'),
            'envelope': u('\ue6e1'),
            'envelope-alt': u('\ue6e0'),
            'error': u('\ue6df'),
            'error-alt': u('\ue6de'),
            'eur': u('\ue6dd'),
            'exclamation-sign': u('\ue6dc'),
            'eye-close': u('\ue6db'),
            'eye-open': u('\ue6da'),
            'facebook': u('\ue6d9'),
            'facetime-video': u('\ue6d8'),
            'fast-backward': u('\ue6d7'),
            'fast-forward': u('\ue6d6'),
            'female': u('\ue6d5'),
            'file': u('\ue6d4'),
            'file-alt': u('\ue6d3'),
            'file-edit': u('\ue6d2'),
            'file-edit-alt': u('\ue6d1'),
            'file-new': u('\ue6d0'),
            'file-new-alt': u('\ue6cf'),
            'film': u('\ue6ce'),
            'filter': u('\ue6cd'),
            'fire': u('\ue6cc'),
            'flag': u('\ue6cb'),
            'flag-alt': u('\ue6ca'),
            'flickr': u('\ue6c9'),
            'folder': u('\ue6c8'),
            'folder-close': u('\ue6c7'),
            'folder-open': u('\ue6c6'),
            'folder-sign': u('\ue6c5'),
            'font': u('\ue6c4'),
            'fontsize': u('\ue6c3'),
            'fork': u('\ue6c2'),
            'forward': u('\ue6c1'),
            'forward-alt': u('\ue6c0'),
            'foursquare': u('\ue6bf'),
            'friendfeed': u('\ue6be'),
            'friendfeed-rect': u('\ue6bd'),
            'fullscreen': u('\ue6bc'),
            'gbp': u('\ue6bb'),
            'gift': u('\ue6ba'),
            'github': u('\ue6b9'),
            'github-text': u('\ue6b8'),
            'glass': u('\ue6b7'),
            'glasses': u('\ue6b6'),
            'globe': u('\ue6b5'),
            'globe-alt': u('\ue6b4'),
            'googleplus': u('\ue6b3'),
            'graph': u('\ue6b2'),
            'graph-alt': u('\ue6b1'),
            'group': u('\ue6b0'),
            'group-alt': u('\ue6af'),
            'guidedog': u('\ue6ae'),
            'hand-down': u('\ue6ad'),
            'hand-left': u('\ue6ac'),
            'hand-right': u('\ue6ab'),
            'hand-up': u('\ue6aa'),
            'hdd': u('\ue6a9'),
            'headphones': u('\ue6a8'),
            'hearing-impaired': u('\ue6a7'),
            'heart': u('\ue6a6'),
            'heart-alt': u('\ue6a5'),
            'heart-empty': u('\ue6a4'),
            'home': u('\ue6a3'),
            'home-alt': u('\ue6a2'),
            'hourglass': u('\ue6a1'),
            'idea': u('\ue6a0'),
            'idea-alt': u('\ue69f'),
            'inbox': u('\ue69e'),
            'inbox-alt': u('\ue69d'),
            'inbox-box': u('\ue69c'),
            'indent-left': u('\ue69b'),
            'indent-right': u('\ue69a'),
            'info-sign': u('\ue699'),
            'instagram': u('\ue698'),
            'iphone-home': u('\ue697'),
            'italic': u('\ue696'),
            'key': u('\ue695'),
            'laptop': u('\ue694'),
            'laptop-alt': u('\ue693'),
            'lastfm': u('\ue692'),
            'leaf': u('\ue691'),
            'lines': u('\ue690'),
            'link': u('\ue68f'),
            'linkedin': u('\ue68e'),
            'list': u('\ue68d'),
            'list-alt': u('\ue68c'),
            'livejournal': u('\ue68b'),
            'lock': u('\ue68a'),
            'lock-alt': u('\ue689'),
            'magic': u('\ue688'),
            'magnet': u('\ue687'),
            'male': u('\ue686'),
            'map-marker': u('\ue685'),
            'map-marker-alt': u('\ue684'),
            'mic': u('\ue683'),
            'mic-alt': u('\ue682'),
            'minus': u('\ue681'),
            'minus-sign': u('\ue680'),
            'move': u('\ue67f'),
            'music': u('\ue67e'),
            'myspace': u('\ue67d'),
            'network': u('\ue67c'),
            'off': u('\ue67b'),
            'ok': u('\ue67a'),
            'ok-circle': u('\ue679'),
            'ok-sign': u('\ue678'),
            'opensource': u('\ue677'),
            'paper-clip': u('\ue676'),
            'paper-clip-alt': u('\ue675'),
            'path': u('\ue674'),
            'pause': u('\ue673'),
            'pause-alt': u('\ue672'),
            'pencil': u('\ue671'),
            'pencil-alt': u('\ue670'),
            'person': u('\ue66f'),
            'phone': u('\ue66e'),
            'phone-alt': u('\ue66d'),
            'photo': u('\ue66c'),
            'photo-alt': u('\ue66b'),
            'picasa': u('\ue66a'),
            'picture': u('\ue669'),
            'pinterest': u('\ue668'),
            'plane': u('\ue667'),
            'play': u('\ue666'),
            'play-alt': u('\ue665'),
            'play-circle': u('\ue664'),
            'plus': u('\ue663'),
            'plus-sign': u('\ue662'),
            'podcast': u('\ue661'),
            'print': u('\ue660'),
            'puzzle': u('\ue65f'),
            'qrcode': u('\ue65e'),
            'question': u('\ue65d'),
            'question-sign': u('\ue65c'),
            'quotes': u('\ue65b'),
            'quotes-alt': u('\ue65a'),
            'random': u('\ue659'),
            'record': u('\ue658'),
            'reddit': u('\ue657'),
            'refresh': u('\ue656'),
            'remove': u('\ue655'),
            'remove-circle': u('\ue654'),
            'remove-sign': u('\ue653'),
            'repeat': u('\ue652'),
            'repeat-alt': u('\ue651'),
            'resize-full': u('\ue650'),
            'resize-horizontal': u('\ue64f'),
            'resize-small': u('\ue64e'),
            'resize-vertical': u('\ue64d'),
            'return-key': u('\ue64c'),
            'retweet': u('\ue64b'),
            'reverse-alt': u('\ue64a'),
            'road': u('\ue649'),
            'rss': u('\ue648'),
            'scissors': u('\ue647'),
            'screen': u('\ue646'),
            'screen-alt': u('\ue645'),
            'screenshot': u('\ue644'),
            'search': u('\ue643'),
            'search-alt': u('\ue642'),
            'share': u('\ue641'),
            'share-alt': u('\ue640'),
            'shopping-cart': u('\ue63f'),
            'shopping-cart-sign': u('\ue63e'),
            'signal': u('\ue63d'),
            'skype': u('\ue63c'),
            'slideshare': u('\ue63b'),
            'smiley': u('\ue63a'),
        }
    },
    # 'raphael': {
    #     'name': 'Raphaël Icons',
    #     'ttf': 'raphaelicons-webfont.ttf',
    #     'credit': 'Dmitry Baranovskiy / Marek Ventur',
    #     'url': 'http://icons.marekventur.de/',
    #     'licence': 'http://creativecommons.org/licenses/MIT/',
    #     # 'woff': 'fontawesome-webfont.woff',
    #     'css': 'elusive.css',
    #     'classgen': lambda s: 'el-icon-' + s,
    #     'characters': {

    #     }
    # },
}

from siteconfig import *
